language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - master
before_install:
  - go install github.com/go-bindata/go-bindata/...
script:
  - go test -v ./...
  - go build
  - export PATH=$PATH:$GOROOT/bin:$GOPATH/bin 
  - ./build-local.sh
  - ./build-release.sh
  - mv ./release/*.tar.gz ./
env:
  - GO111MODULE=on
notifications:
  email:
    recipients:
      - 1151510533@qq.com
    on_success: always
deploy:
  provider: releases
  api_key:
    secure: $GH_TOKEN
  file_glob: true
  file: "*.tar.gz"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION =~ ^1\.13